@startuml カレーライス
title カレーライスの作り方
|Aさん|
|Aさん|
|Bさん|
|Bさん|
|Cさん|
|Cさん|

|Bさん|
start
:野菜と肉を準備する;
fork
|Aさん|
    :お米を研ぐ;
    :お米を炊く;
|Aさん|
fork again
|Bさん|
    :野菜を切る;
    :肉を切る;
    :肉を炒める;
    :野菜を炒める;
    :鍋に水を入れる;
    :鍋にカレールーを入れる;
    :煮込む;
|Bさん|
end fork
|Aさん|
:皿にご飯を盛り付ける;
|Bさん|
:皿にカレーをかける;
|Cさん|
:カレーライス]
:カレーライスを食べる;
@enduml