@startuml 演習3-2 
left to right direction

class 医局 {
    ---
}
class 医師 {
---
+ 診察する()
+ 診察記録の作成()
}
class 患者{
---
}
class 診察記録 {
---
}

医師 "1  作成者" --> "作成物 *" 診察記録:作成する
医師 "1  担当医" ---> "患者  *" 患者:担当する
医師 "*"-->"1" 医局  :所属する
患者 "1"---"*" 診察記録
@enduml