@startuml 演習6-4-2
    left to right direction 
    actor 客 as person #DDDDDD;line:black;line.bold;
    actor ベンダー as bender #DDDDDD;line:black;line.bold;
    rectangle 自動販売機{
        usecase (自動販売機の\nお金を回収) as text1
        usecase (お金を入れる) as text2
        usecase (ドリンクを買う) as text3
    }
    person-->text3
    text3<.down.text2: <<include>>
    text1<--bender
@enduml