@startuml 演習6-3
    [*]-right->メニュー画面
    メニュー画面--down->予約と確認画面: 予約と確認ボタン\nを押す
    メニュー画面<-up--予約と確認画面: 取り消しボタン\nを押す
    メニュー画面<-up--あなたの順番: メニューボタン\nを押す
    予約と確認画面--right->あなたの順番: 登録ボタンを押す
    予約と確認画面--right->あなたの順番:　確認ボタンを押す
    メニュー画面<-up--今の順番: メニューボタン\nを押す
    メニュー画面--down->今の順番: 今の順番ボタンを\n押す
    メニュー画面-right->[*]
@enduml